import Navbar from "@/components/navbar/Navbar";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Footer from "@/components/footer/Footer";
import { Container, Paper } from "@mui/material";
import ThemeRegistry from "./ThemeRegistry";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "my App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeRegistry options={{ key: "mui" }}>
          <Paper>
            <Container>
              <Navbar />
              {children}
              <Footer />
            </Container>
          </Paper>
        </ThemeRegistry>
      </body>
    </html>
  );
}
